FROM public.ecr.aws/lambda/python:3.9

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY lambda_function.py .
COPY report_generator.py .
COPY load.py .

CMD ["lambda_function.lambda_handler"]
